{% set name = "mathjax" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mathjax/MathJax/archive/{{ version }}.tar.gz
  sha256: 0f234da8c0198576101cad9646753bce10e3c9db6f323220403eca7a819271c9

build:
  number: 0

test:
  commands:
    - mathjax-path  # [unix]
    - test -f "$(mathjax-path)tex-chtml.js"  # [unix]
    - cmd /c "%PREFIX%\Scripts\mathjax-path.bat"  # [win]
    - if exist "%PREFIX%\Library\lib\mathjax\tex-chtml.js" (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/mathjax/MathJax
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Beautiful math in all browsers. MathJax is an open-source JavaScript display engine for LaTeX, MathML, and AsciiMath notation that works in all browsers. (use mathjax-path script)
  doc_url: https://github.com/mathjax/MathJax
  dev_url: https://github.com/mathjax/MathJax

extra:
  recipe-maintainers:
    - kiwi0fruit
    - tdegeus
