{% set name = "mathjax" %}
{% set version = "3.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mathjax/MathJax/archive/{{ version }}.tar.gz
  sha256: 5bf53c321f71ebba8d0ade9183a5570a0d2e64f8322e4a58b696328ef438b7b5

build:
  number: 0

requirements:
  build:
    - conda-forge: :git  # [win]

test:
  commands:
    - mathjax-path  # [unix]
    - test -f "$(mathjax-path)latest.js"  # [unix]
    - cmd /c "%PREFIX%\Scripts\mathjax-path.bat"  # [win]
    - bash "%PREFIX%\Scripts\mathjax-path"  # [win]

about:
  home: https://github.com/mathjax/MathJax
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Beautiful math in all browsers. MathJax is an open-source JavaScript display engine for LaTeX, MathML, and AsciiMath notation that works in all browsers. (use mathjax-path script)
  doc_url: https://github.com/mathjax/MathJax
  dev_url: https://github.com/mathjax/MathJax

extra:
  recipe-maintainers:
    - kiwi0fruit
