travis:
  secure:
    BINSTAR_TOKEN: sFG9BEGLklcE1bRTqVipvx44c7XU9nZYOHq1UNZItBzo83ArOyCoWd7OIA+P81EWn4VtKWDMdjpjh6xmQl3SOoce+NB5XZebC4Yg7zUuxq1h8G+hml8HoTAwuwlYFXdERWDY3ud2tGkmQDnwwTpw63eXAp1z8MYn38E/rK8cd2BtU65W3roioH2eFY2691KpbJrLpx3EVOqQAmh/Hu2/eMicIi5Uxmn5nidS95jEVR24liQm68Wdc5IQh3Ck4hWqK0gGbU7aM/xOfa7kfUNg1bJo8rrjwxq6ZHc6PsW6LK1HhWDpASqciA2C2WbIqSHEU+92Az15EIBjsAtw7UhxMXJxo44gS3i17A6A9/wj/jw2ekfwRoSCjNyyVoCh+DZFL3dZjDUS6iTFGWPkCsdUMR/kAHtd70YAc+ZV9ue8bLF1ucVj56NV1KbQWOwoPAO6XsquGc4/s5OELFyPuilTiJKnC1/e829EnHN++3dpVMsF1zJyl/qRVZpsE0HlGo72qLi/iLiD/H3fIugjg5Oane7WNv9xQJAtw+zwxk2nGtBcwGsx8nkrwOU0hRTW0ZFaXO4EICtajXi8l49NOjYXp1EtrZuUx238ImN5rhAzGWcyuKPAKzRujf0uxk8ureMW65jXNthDq7ulcdzNJLm8FqTK54f97rqJ+kJ74gXZl9A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
